-- Import the 20 current 2026 clients/events. Safe to run more than once.
insert into public.leads
(id,name,partner,email,phone,event_type,event_date,guests,source,status,assigned_staff,follow_up_date,lost_reason,notes,created_at,updated_at,updated_by)
values
('seed-2026-01','Red, White, and Rhapsody in Blue',null,null,null,'Other','2026-06-19',200,'Existing Schedule','booked','Matt, Margeaux, Kendra, Mike',null,null,'Imported from 2026 Event Schedule. Timing: Friday 7:30 PM show start. Spaces: Auditorium; Conference Room. Contract signed: Yes.',now(),now(),null),
('seed-2026-02','Houghtaling 50th Anniversary Party',null,null,null,'Private Event','2026-07-10',75,'Existing Schedule','booked','Matt, Margeaux',null,null,'Imported from 2026 Event Schedule. Timing: 3:30 PM–9:30 PM. Spaces: Auditorium; Conference Room. Contract signed: Yes.',now(),now(),null),
('seed-2026-03','Bridal Shower: Katie Jammer',null,null,null,'Private Event','2026-07-19',0,'Existing Schedule','lost','Margeaux',null,'Cancelled on schedule','Imported from 2026 Event Schedule. Timing: Not listed. Spaces: Conference Room. Contract signed: Yes.',now(),now(),null),
('seed-2026-04','Sophie Allen Ceremony Rehearsal',null,null,null,'Wedding','2026-07-31',0,'Existing Schedule','booked','Kendra, Mike',null,null,'Imported from 2026 Event Schedule. Timing: Rehearsal. Spaces: Auditorium. Contract signed: Yes.',now(),now(),null),
('seed-2026-05','Ceremony: Sophie Allen',null,null,null,'Wedding','2026-08-01',125,'Existing Schedule','booked','Kendra, Mike',null,null,'Imported from 2026 Event Schedule. Timing: 7:00 AM–6:30 PM. Spaces: Auditorium; Bridal Suite; Groom’s Room. Contract signed: Yes.',now(),now(),null),
('seed-2026-06','Great Lakes Bay Mental Health Connect Networking Event',null,null,null,'Nonprofit Event','2026-08-06',90,'Existing Schedule','booked','Matt, Margeaux',null,null,'Imported from 2026 Event Schedule. Timing: 4:30 PM–8:30 PM. Spaces: Conference Room. Contract signed: Unknown.',now(),now(),null),
('seed-2026-07','Daniel Purifoy Wedding',null,null,null,'Wedding','2026-08-22',60,'Existing Schedule','lost',null,null,'Cancelled on schedule','Imported from 2026 Event Schedule. Timing: 9:00 AM setup. Spaces: Conference Room. Contract signed: No.',now(),now(),null),
('seed-2026-08','A Night to Remember',null,null,null,'Private Event','2026-08-27',150,'Existing Schedule','booked','Matt, Margeaux',null,null,'Imported from 2026 Event Schedule. Timing: Evening. Spaces: Ballroom. Contract signed: No.',now(),now(),null),
('seed-2026-09','Alexis Miller Wedding',null,null,null,'Wedding','2026-09-12',0,'Existing Schedule','booked','Matt, Margeaux, Kendra',null,null,'Imported from 2026 Event Schedule. Timing: 7:00 AM–11:00 PM. Spaces: Ballroom; Auditorium; Bridal Suite; Groom’s Room. Contract signed: Yes.',now(),now(),null),
('seed-2026-10','Wendy Williams Wedding',null,null,null,'Wedding','2026-09-19',80,'Existing Schedule','booked','Matt, Margeaux, Mike',null,null,'Imported from 2026 Event Schedule. Timing: Eight-hour block. Spaces: Auditorium; Conference Room. Contract signed: Yes.',now(),now(),null),
('seed-2026-11','5/3 Event',null,null,null,'Corporate Event','2026-09-25',0,'Existing Schedule','booked',null,null,null,'Imported from 2026 Event Schedule. Timing: Not listed. Spaces: Ballroom. Contract signed: No.',now(),now(),null),
('seed-2026-12','Tom Hardy + Carmen Lozano Wedding Ceremony',null,null,null,'Wedding','2026-09-26',100,'Existing Schedule','booked','Matt, Margeaux, Kendra, Mike',null,null,'Imported from 2026 Event Schedule. Timing: Noon–3:00 PM. Spaces: Auditorium. Contract signed: Yes.',now(),now(),null),
('seed-2026-13','Jupiter Market',null,null,null,'Private Event',null,600,'Existing Schedule','booked','Matt, Margeaux, Kendra, Mike',null,null,'Imported from 2026 Event Schedule. Timing: September, 4:00 PM–9:30 PM. Spaces: Ballroom. Contract signed: Yes.',now(),now(),null),
('seed-2026-14','Glorida + Richie David Anniversary Party',null,null,null,'Private Event','2026-10-03',150,'Existing Schedule','booked','Matt, Margeaux',null,null,'Imported from 2026 Event Schedule. Timing: 4:00 PM–11:00 PM. Spaces: Ballroom. Contract signed: Unknown.',now(),now(),null),
('seed-2026-15','Kendra Keyes Reception',null,null,null,'Wedding','2026-10-10',225,'Existing Schedule','booked','Matt, Margeaux',null,null,'Imported from 2026 Event Schedule. Timing: Evening until 11:00 PM. Spaces: Ballroom. Contract signed: Yes.',now(),now(),null),
('seed-2026-16','Ava Rummler Ceremony + Reception',null,null,null,'Wedding','2026-10-17',0,'Existing Schedule','booked','Matt, Margeaux, Mike',null,null,'Imported from 2026 Event Schedule. Timing: 7:00 AM–11:00 PM. Spaces: Ballroom; Auditorium; Bridal Suite; Groom’s Room. Contract signed: Yes.',now(),now(),null),
('seed-2026-17','Scottish Rite Reunion - Friday',null,null,null,'Private Event','2026-10-23',0,'Existing Schedule','booked',null,null,null,'Imported from 2026 Event Schedule. Timing: 5:00 PM–10:00 PM. Spaces: Not listed. Contract signed: Yes.',now(),now(),null),
('seed-2026-18','Scottish Rite Reunion - Saturday',null,null,null,'Private Event','2026-10-24',0,'Existing Schedule','booked',null,null,null,'Imported from 2026 Event Schedule. Timing: TBD. Spaces: Not listed. Contract signed: Yes.',now(),now(),null),
('seed-2026-19','Marissa Townsend Wedding',null,null,null,'Wedding','2026-10-30',300,'Existing Schedule','booked','Matt, Margeaux, Mike',null,null,'Imported from 2026 Event Schedule. Timing: 7:00 AM–11:00 PM. Spaces: Ballroom; Auditorium; Bridal Suite; Groom’s Room. Contract signed: Yes.',now(),now(),null),
('seed-2026-20','Lyndsay Meyers Book Event',null,null,null,'Other','2026-11-07',0,'Existing Schedule','lost','Kendra',null,'Cancelled on schedule','Imported from 2026 Event Schedule. Timing: Not listed. Spaces: Auditorium; Conference Room; Bridal Suite. Contract signed: Yes.',now(),now(),null)
on conflict (id) do update set
 name=excluded.name,event_type=excluded.event_type,event_date=excluded.event_date,
 guests=excluded.guests,status=excluded.status,assigned_staff=excluded.assigned_staff,
 lost_reason=excluded.lost_reason,notes=excluded.notes,updated_at=now();
